server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.115.129:3306/guli_cart
    username: root
    password: root
  redis:
    host: 192.168.115.129
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        max-size: 100
        keep-alive: 60s
        core-size: 50
        queue-capacity: 1000
        allow-core-thread-timeout: false #线程可伸缩
      shutdown:
        await-termination: true #是否等待任务完成
        await-termination-period: 60 #等待时间
  rabbitmq:
    host: 192.168.115.129
    virtual-host: /wuhao
    username: wuhao
    password: wuhao
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 4 #多线程消费

feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\project\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: user-key
    expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto