server:
  port: 18085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.115.1:8848
    sentinel:
      transport:
        dashboard: 192.168.115.1:8080
        port: 8719
  zipkin:
    base-url: http://192.168.115.1:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.115.129:3306/guli_oms
    username: root
    password: root
  redis:
    host: 192.168.115.129
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto