server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.115.1:8848
    gateway:
      routes:
        - id: pms-route #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://pms-service #匹配后提供服务的路由地址
          predicates:
            - Path=/pms/**  #断言，路径相匹配的进行路由
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
