server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.115.1:8848
    gateway:
      routes:
        - id: pms-route #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://pms-service #匹配后提供服务的路由地址
          predicates:
            - Path=/pms/**  #断言，路径相匹配的进行路由
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com


        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/


auth:
  jwt:
    pubKeyPath: D:\project\rsa\rsa.pub
    cookieName: GMALL-TOKEN

